### ISSUE TITLE
能否参数，可以设置请求的UA

### ISSUE THREAD

**Issue by sln162** [j4587698/AListSdkSharp#2]
比如使用fs/get接口，获取到的raw_url下载链接，一般的网盘是可以直接下载的，但部分网盘有UA验证，比如115，没办法在外部直接下载，如下图，只能用您的SDK内置的下载文件到本地。

![image](https://github.com/user-attachments/assets/6d20fe94-5f92-4b08-8f6e-2ab96d9128be)

希望可以增加选项，设置请求get接口时的UA，这样Alist这边会用设置的UA去生成raw_url。

![image](https://github.com/user-attachments/assets/c1dc39ff-64bc-4b66-bac1-f12efb03a09e)
![image](https://github.com/user-attachments/assets/c097a0b9-5b02-4d4d-9da4-b9a473627bdf)

[用API获取的115直链不可用](https://github.com/alist-org/alist/issues/5836)

**Comment by j4587698** [comment]
v1.1.4
Download DownloadRange增加了一个Headers参数，参数是元组，可以任意设置标头，例如需要增加UA，可以配置
```
await fs.Download(RawUrl, new CancellationToken(), ("User-Agent", "AListSharp/1.0"));
```

**Comment by j4587698** [comment]
其实还可以直接配置flurl的全局配置，在调用以前的任何地方可以配置类似
```
FlurlHttp.Clients.WithDefaults(builder => builder.WithHeader("User-Agent", "AListSharp/1.0"));
```
这样所有flurl发出的请求都会统一使用相同的UA

**Comment by sln162** [comment]
> v1.1.4 Download DownloadRange增加了一个Headers参数，参数是元组，可以任意设置标头，例如需要增加UA，可以配置
> 
> ```
> await fs.Download(RawUrl, new CancellationToken(), ("User-Agent", "AListSharp/1.0"));
> ```

非常感谢您的及时更新，但您误解我的意思了，需要UA验证的地方不是Download方法，而是Info方法。
```
var c = await fs.Info(token, new ListIn()
{
    Path = item + "/" + fileName,
});
```


> 其实还可以直接配置flurl的全局配置，在调用以前的任何地方可以配置类似
> 
> ```
> FlurlHttp.Clients.WithDefaults(builder => builder.WithHeader("User-Agent", "AListSharp/1.0"));
> ```
> 
> 这样所有flurl发出的请求都会统一使用相同的UA

这样是可以修改全局的，但是面向分享时，无法得知别人浏览器的UA，所以是动态的，每次修改全局是很糟糕的，因为还有并发的可能性。

**Comment by sln162** [comment]
@j4587698  能否麻烦您在Info方法增加个Headers参数

**Comment by j4587698** [comment]
v1.1.5，Info增加了headers参数

**Comment by sln162** [comment]
非常感谢！
