### ISSUE TITLE
请求增加Alist的禁用和启用某个存储的方法

### ISSUE THREAD

**Issue by sln162** [j4587698/AListSdkSharp#7]
https://alist.nn.ci/zh/guide/api/admin/storage.html

![image](https://github.com/user-attachments/assets/69d330ed-89a3-453e-a9e1-e4d371a7350a)
能否增加这三个方法，因为发现有这个问题：https://github.com/AlistGo/alist/issues/7288
所以想自己在后台通过api去解决，如果您有时间，不知可否增加一下，谢谢

**Comment by j4587698** [comment]
等有空研究研究看看，好做的话就做上

**Comment by j4587698** [comment]
发布了1.2.0，增加了Storage类，
var storage = new Storage(baseUrl); // 创建一个Storage对象
var b = await storage.List(token); // 获取文件列表
var d = await storage.Disable(token, 2); // 禁用指定id的存储
var c = await storage.Enable(token, 2); // 启用指定id的存储

如果没有问题，请关闭issue，感谢

**Comment by sln162** [comment]
非常感谢，实测可用
